all: $(EXECUTABLE) python_embed/wrapper_functions.so

debug: CXXFLAGS += -g
debug: CXXFLAGS += -O0
debug: CPPFLAGS += -DDEBUG
debug: all


#
# The other makefile
#

tmx-parser/libtmxparser.a: tmx-parser/Makefile.linux
	@echo "${bold}[ Compiling tmx-parser library ]${normal}"
	@if [ "$(SANITIZE)" == "1" ]; then \
		$(MAKE) -C tmx-parser -f Makefile.linux; \
	else \
		$(MAKE) CXXFLAGS=-fPIC -C tmx-parser -f Makefile.linux; \
	fi


#
# Folders
#

dependencies:
	@-${MKDIR} dependencies

dependencies/gui: | dependencies
	@-${MKDIR} dependencies/gui

dependencies/python_embed: | dependencies
	@-${MKDIR} dependencies/python_embed

dependencies/challenges: | dependencies
	@-${MKDIR} dependencies/challenges

dependencies/input_management: | dependencies
	@-${MKDIR} dependencies/input_management


#
# Executables
#

$(EXECUTABLE): $(BASE_OBJS) $(CHALLENGE_OBJS) $(INPUT_OBJS) $(PYTHON_OBJS) tmx-parser/libtmxparser.a | dependencies
	@echo "${bold}${red}[ Compiling $(EXECUTABLE) ]${normal}"

	@$(COMPILER) -o $@ \
		$(BASE_OBJS) $(CHALLENGE_OBJS) $(INPUT_OBJS) $(PYTHON_OBJS) \
		$(BOOST_LDFLAGS)     $(BOOST_LDLIBS)     $(BOOST_CXXFLAGS)     \
		$(GLOG_LDFLAGS)      $(GLOG_LDLIBS)      $(GLOG_CXXFLAGS)      \
		$(GRAPHICS_LDFLAGS)  $(GRAPHICS_LDLIBS)  $(GRAPHICS_CXXFLAGS)  \
		$(PYTHON_LDFLAGS)    $(PYTHON_LDLIBS)    $(PYTHON_CXXFLAGS)    \
		$(SDL_LDFLAGS)       $(SDL_LDLIBS)       $(SDL_CXXFLAGS)       \
		$(TINYXML_LDFLAGS)   $(TINYXML_LDLIBS)   $(TINYXML_CXXFLAGS)   \
		$(TMXPARSER_LDFLAGS) $(TMXPARSER_LDLIBS) $(TMXPARSER_CXXFLAGS) \
		$(X11_LDFLAGS)       $(X11_LDLIBS)       $(X11_CXXFLAGS)       \
		$(ZLIB_LDFLAGS)      $(ZLIB_LDLIBS)      $(ZLIB_CXXFLAGS)      \
		$(LDLIBS)            $(LDFLAGS)          $(CXXFLAGS)


#
# Object files
#

$(BASE_OBJS): %.o : %.cpp | dependencies
	@echo "${bold}[ Compiling base object file ${red}$*.o${normal}${bold} from ${red}$*.cpp${normal}${bold} ]${normal}"

	@# Need $(PYTHON_CPPFLAGS) due to internal layout of Interpreter object.
	@# This should not cause a large slowdown unless actually included in many files.
	@$(COMPILER) -c $*.cpp -o $*.o \
		$(GLOG_CPPFLAGS)      $(GLOG_CXXFLAGS)      \
		$(GRAPHICS_CPPFLAGS)  $(GRAPHICS_CXXFLAGS)  \
		$(PYTHON_CPPFLAGS)    $(PYTHON_CXXFLAGS)    \
		$(SDL_CPPFLAGS)       $(SDL_CXXFLAGS)       \
		$(TINYXML_CPPFLAGS)   $(TINYXML_CXXFLAGS)   \
		$(TMXPARSER_CPPFLAGS) $(TMXPARSER_CXXFLAGS) \
		$(X11_CPPFLAGS)       $(X11_CXXFLAGS)       \
		$(ZLIB_CPPFLAGS)      $(ZLIB_CXXFLAGS)      \
		$(CPPFLAGS)           $(CXXFLAGS)

$(INPUT_OBJS): %.o : %.cpp | dependencies/input_management
	@echo "${bold}[ Compiling input object file ${red}$*.o${normal}${bold} from ${red}$*.cpp${normal}${bold} ]${normal}"

	@$(COMPILER) -c $*.cpp -o $*.o \
		$(GLOG_CPPFLAGS) $(GLOG_CXXFLAGS) \
		$(SDL_CPPFLAGS)  $(SDL_CXXFLAGS)  \
		$(CPPFLAGS)      $(CXXFLAGS)

$(CHALLENGE_OBJS): %.o : %.cpp | dependencies/challenges
	@echo "${bold}[ Compiling challenge object file ${red}$*.o${normal}${bold} from ${red}$*.cpp${normal}${bold} ]${normal}"

	@$(COMPILER) -c $*.cpp -o $*.o \
		$(GLOG_CPPFLAGS)     $(GLOG_CXXFLAGS)     \
		$(GRAPHICS_CPPFLAGS) $(GRAPHICS_CXXFLAGS) \
		$(PYTHON_CPPFLAGS)   $(PYTHON_CXXFLAGS)   \
		$(CPPFLAGS)          $(CXXFLAGS)

$(PYTHON_OBJS): %.o : %.cpp $(PYTHON_HEADER).$(PRECOMPILED_HEADER_EXTENSION) | dependencies/python_embed
	@echo "${bold}[ Compiling Python object file ${red}$*.o${normal}${bold} from ${red}$*.cpp${normal}${bold} ]${normal}"

	@$(COMPILER) -c $*.cpp -o $*.o \
		$(GLOG_CPPFLAGS)                      \
		$(PYTHON_CPPFLAGS) $(PYTHON_CXXFLAGS) \
		$(PYTHON_INCLUDE_PCH)                 \
		$(CXXFLAGS) $(CPPFLAGS)

$(PYTHON_SHARED_OBJS): %.so : %.cpp $(PYTHON_SHARED_OBJS_DEPENDS) | dependencies/python_embed
	@echo "${bold}[ Compiling Python shared object file ${red}$*.so${normal}${bold} from ${red}$*.cpp${normal}${bold} ]${normal}"

	@$(COMPILER) -shared -fPIC $*.cpp -o $*.so \
		$(PYTHON_LDLIBS) $(PYTHON_CPPFLAGS) \
		$(BOOST_LDLIBS) $(BOOST_CPPFLAGS)   \
		$(CXXFLAGS) $(CPPFLAGS) \
		-MF dependencies/$*.sd


#
# Precompiled header
#

$(PYTHON_HEADER).unknown:
	@echo "${bold}[ $(COMPILER): ${RED}Don't know how to precompiling Python header; ignoring.${normal}${bold} ]${normal}"
	@touch $(PYTHON_HEADER).unknown

$(PYTHON_HEADER).gch: $(PYTHON_HEADER)
	@echo "${bold}[ $(COMPILER): Precompiling Python header ${red}$<.gch${normal}${bold} from ${red}$<${normal}${bold} ]${normal}"

	@$(COMPILER) $< -o $<.gch \
		$(PYTHON_CPPFLAGS) $(PYTHON_CXXFLAGS) \
		$(CPPFLAGS)        $(CXXFLAGS)

# This largely assumes the setup is constant for clang.
# clang with precompiled headers may work, but is not guaranteed.
$(PYTHON_HEADER).pch: $(PYTHON_HEADER)
	@echo "${bold}[ $(COMPILER): Precompiling Python header ${red}$<.pch${normal}${bold} from ${red}$<${normal}${bold} ]${normal}"

	@# Apologies for the mess, but I can't think of a better way.
	@$(COMPILER) -x c++-header $< -o $<.pch \
		$$(echo                                       \
			"$(BOOST_CPPFLAGS)" "$(BOOST_CXXFLAGS)"   \
			"$(PYTHON_CPPFLAGS)" "$(PYTHON_CXXFLAGS)" \
			"$(CXXFLAGS)"                             \
		| sed                       \
		 	-e 's/-mtune=[^ ]*//g'  \
		 	-e 's/-generic//g'      \
		 	-e 's/--param=[^ ]*//g' \
		 	-e 's/-M[^ ]*//g'       \
		)


#
# Once finished...
#

debug:
	@echo "${bold}${red}Complied in debug${normal}"


#
# Cleaning
#

# Dependency hack to keep away uninteresting errors
clean: dependencies dependencies/python_embed dependencies/challenges dependencies/input_management
	@-$(RM) $(EXECUTABLE) 

	@-$(RM) \
		$(BASE_OBJS)          \
		$(CHALLENGE_OBJS)     \
		$(INPUT_OBJS)         \
		$(PYTHON_OBJS)        \
		$(PYTHON_SHARED_OBJS)

	@-$(RM) $(HEADER_DEPENDS)

	@-$(RMDIR) \
		dependencies/challenges       \
		dependencies/input_management \
		dependencies/python_embed     \
		dependencies

	@echo "${bold}${red}Made clean${normal}"

veryclean: clean
	@-$(RM) $(PYTHON_HEADER).gch $(PYTHON_HEADER).pch
	@-$(MAKE) -C tmx-parser -f Makefile.linux clean
	@echo "${bold}${red}Made very clean${normal}"

-include ${HEADER_DEPENDS}


#
# It is what it is, OK?
#

.PHONY: all
.PHONY: clean
.PHONY: debug
.PHONY: veryclean
